### ISSUE TITLE
CIFAR config

### ISSUE THREAD

**Issue by YAaNnGg** [WangFeng18/InvariancePropagation#2]
Hi! Thanks for your inspiring work.

I notice there is some code about CIFAR training in this repository. Could you please specify one complete config of this part for a fast validation like 'resnet18 + cifar100'?

Thanks a lot!

**Comment by WangFeng18** [comment]
Hi,
Thanks for giving the advice. I have complete the cifar10/cifar100/svhn config in README.
Feng.

**Comment by YAaNnGg** [comment]
Thanks again for your update!
